---
- name: Update all Ubuntu packages
  apt:
    upgrade: "dist"
  when: ansible_distribution == 'Ubuntu'

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - openjdk-8-jdk
